"""Regenerate docs/COMMIT-HISTORY.md from git log.

This repo has no remote. A zip may be copied without its `.git` directory,
and then the reasoning behind every decision is gone. A plain-text record
costs nothing and survives that.

    python scripts/gen_commit_history.py
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "docs" / "COMMIT-HISTORY.md"

HEADER = """# Commit history

Generated by `scripts/gen_commit_history.py`. **Do not hand-edit** -- rerun
the script instead.

This repo has no git remote. If you received it as a zip without `.git`,
this file is the only record of how it got here. If you do have `.git`,
`git log` is authoritative and this is a convenience.

It is generated *before* the commit that records it, so it always lags the
most recent commit by one. That is unavoidable for a file that documents its
own history, and harmless.

"""


def git(*args: str) -> str:
    result = subprocess.run(
        ["git", *args], cwd=str(REPO), capture_output=True, text=True,
        encoding="utf-8", errors="replace",
    )
    if result.returncode != 0:
        raise SystemExit(f"git {' '.join(args)} failed: {result.stderr.strip()}")
    return result.stdout


def main() -> int:
    raw = git("log", "--reverse", "--pretty=%H%x1f%h%x1f%an%x1f%ad%x1f%s%x1f%b%x1e", "--date=short")
    entries = [e for e in raw.split("\x1e") if e.strip()]

    lines = [HEADER, f"{len(entries)} commit(s), oldest first.\n"]
    for entry in entries:
        parts = entry.strip("\n").split("\x1f")
        if len(parts) < 5:
            continue
        full, short, author, date, subject = parts[:5]
        body = parts[5].strip() if len(parts) > 5 else ""
        lines.append(f"\n---\n\n## `{short}` — {subject}\n")
        lines.append(f"- **date:** {date}")
        lines.append(f"- **author:** {author}")
        lines.append(f"- **sha:** `{full}`\n")
        if body:
            lines.append(body.rstrip() + "\n")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines).replace("\r\n", "\n"), encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(REPO)} ({len(entries)} commits)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
