"""Package the repo as a handoff zip.

    python scripts/make_zip.py

Writes to the *parent* directory, never inside the repo -- an archive that
contains itself is a classic and annoying mistake.

`.git` is included on purpose. History is the most valuable thing here:
`CLAUDE.md` says what the invariants are, but only the commits say what
broke and why the code is shaped the way it is. If you do not want it, pass
`--no-git`.
"""

from __future__ import annotations

import argparse
import sys
import zipfile
from datetime import date
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

#: Reproducible from source, or machine-specific. Never worth shipping.
EXCLUDED_DIRS = {
    "__pycache__",
    ".venv",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "node_modules",
}

#: Run artifacts. The wiki and skills in `workspace/` are committed as empty
#: scaffolding; traces and run state are regenerated by any run.
EXCLUDED_PREFIXES = (
    "workspace/.state/",
    "workspace/raw/iter-",
    "workspace/raw/eval-",
)

EXCLUDED_SUFFIXES = (".pyc", ".pyo", ".zip")


def should_include(rel: Path, include_git: bool) -> bool:
    parts = rel.parts
    if not include_git and parts and parts[0] == ".git":
        return False
    if any(part in EXCLUDED_DIRS for part in parts):
        return False
    posix = rel.as_posix()
    if any(posix.startswith(prefix) for prefix in EXCLUDED_PREFIXES):
        return False
    if rel.suffix in EXCLUDED_SUFFIXES:
        return False
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--no-git", action="store_true", help="omit .git (smaller, loses history)")
    parser.add_argument("--out", type=Path, default=None)
    args = parser.parse_args(argv)

    stamp = date.today().isoformat()
    suffix = "-source" if args.no_git else ""
    out = args.out or REPO.parent / f"{REPO.name}-{stamp}{suffix}.zip"

    files = [
        p for p in sorted(REPO.rglob("*"))
        if p.is_file() and should_include(p.relative_to(REPO), not args.no_git)
    ]

    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
        for path in files:
            zf.write(path, arcname=str(Path(REPO.name) / path.relative_to(REPO)))

    size_mb = out.stat().st_size / (1024 * 1024)
    print(f"wrote {out}")
    print(f"  {len(files)} files, {size_mb:.1f} MB, git {'included' if not args.no_git else 'omitted'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
